version : '3'
services:
  mysql:
    container_name: mysql
    restart: always
    build:
      dockerfile: ./mysql/Dockerfile
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=ink"
      - "MYSQL_ROOT_HOST=%"
    ports:
      - 13307:3307
    networks:
      - net-ink
    volumes:
       - ./data/mysql:/var/lib/mysql
    command: [
          'mysqld',
          '--innodb-buffer-pool-size=20M',
          '--character-set-server=utf8',
          '--collation-server=utf8_general_ci',
          '--default-time-zone=+8:00',
          '--lower-case-table-names=1'
        ]

  ink:
    container_name: ink
    restart: always
    build:
      dockerfile: ./ink/Dockerfile
    ports:
      - 18080:8080
    networks:
      - net-ink
    volumes:
      - ./data/ink:/opt/ink
    depends_on:
      - mysql
    links:
      - mysql

networks:
  net-ink:
    driver: bridge