version : '3'
services:
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    networks:
      - net-ink
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - upload:/opt/app/upload

  mysql:
    container_name: mysql
    restart: always
    build:
      context: ./mysql
      dockerfile: ./Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ink
      MYSQL_ROOT_HOST: '%'
    ports:
      - "13306:3306"
    networks:
      - net-ink
    volumes:
       - ./data/mysql:/var/lib/mysql
    command: [
          'mysqld',
          '--innodb-buffer-pool-size=20M',
          '--character-set-server=utf8',
          '--collation-server=utf8_general_ci',
          '--default-time-zone=+8:00',
          '--lower-case-table-names=1'
        ]

  app:
    container_name: app
    restart: always
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "18080:8080"
    networks:
      - net-ink
    volumes:
      - ./data/app/logs:/opt/app/logs
      - upload:/opt/app/upload
    depends_on:
      - nginx
      - mysql
    links:
      - mysql

networks:
  net-ink:
    driver: bridge


volumes:
  upload: