-- MySQL Script generated by MySQL Workbench
-- Wed Dec 26 22:35:20 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ink
-- -----------------------------------------------------
-- ink博客系统的数据库
DROP SCHEMA IF EXISTS `ink` ;

-- -----------------------------------------------------
-- Schema ink
--
-- ink博客系统的数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ink` DEFAULT CHARACTER SET utf8 ;
USE `ink` ;

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `id` BIGINT NOT NULL COMMENT '用户id',
  `deleted` TINYINT(1) NOT NULL COMMENT '是否已经被删除了',
  `active` TINYINT(1) NOT NULL COMMENT '是否处于激活状态',
  `permanent` TINYINT(1) NOT NULL COMMENT '是否是长期用户\ntrue：是\nfalse：不是',
  `username` VARCHAR(45) NULL COMMENT '用户名，由字母、数字、下划线组成，长度在30以下，不能重复',
  `password` VARCHAR(200) NULL COMMENT '密码加盐bcrypt散列之后的值',
  `display_name` VARCHAR(45) NULL COMMENT '显示的用户名',
  `email` VARCHAR(200) NULL COMMENT '邮箱，不能重复',
  `home_url` VARCHAR(200) NULL COMMENT '用户的主页，不能重复',
  `salt` VARCHAR(100) NULL COMMENT '加密的盐，这个用户所有需要生成摘要的地方都用这个',
  `last_login` TIMESTAMP NULL COMMENT '最近一次登陆时间',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建用户的时间戳',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新的时间戳',
  `create_by` BIGINT NOT NULL COMMENT '被谁创建',
  `update_by` BIGINT NOT NULL COMMENT '被谁修改',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '用户表';


-- -----------------------------------------------------
-- Table `roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roles` ;

CREATE TABLE IF NOT EXISTS `roles` (
  `id` BIGINT NOT NULL COMMENT '角色id',
  `deleted` TINYINT(1) NOT NULL COMMENT '是否已经被删除',
  `active` TINYINT(1) NOT NULL COMMENT '是否处于激活状态',
  `role` VARCHAR(45) NOT NULL COMMENT '角色名',
  `detail` TEXT NULL COMMENT '角色的详细说明',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `update_by` BIGINT NOT NULL COMMENT '是由那个用户修改的',
  `create_by` BIGINT NOT NULL COMMENT '被谁创建',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '角色';


-- -----------------------------------------------------
-- Table `user_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_roles` ;

CREATE TABLE IF NOT EXISTS `user_roles` (
  `id` BIGINT NOT NULL COMMENT '用户角色记录的id',
  `deleted` TINYINT(1) NOT NULL COMMENT '是否已经被删除',
  `active` TINYINT(1) NOT NULL COMMENT '是否处于激活状态',
  `user_id` BIGINT NOT NULL COMMENT '用户id',
  `role_id` BIGINT NOT NULL COMMENT '角色id',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建用户的时间戳',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建用户的时间戳',
  `create_by` BIGINT NOT NULL COMMENT '被谁创建',
  `update_by` BIGINT NOT NULL COMMENT '被谁修改',
  INDEX `fk_roles_has_users_users1_idx` (`user_id` ASC),
  INDEX `fk_roles_has_users_roles_idx` (`role_id` ASC),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '用户权限映射表';


-- -----------------------------------------------------
-- Table `contents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `contents` ;

CREATE TABLE IF NOT EXISTS `contents` (
  `id` BIGINT NOT NULL COMMENT '内容的id',
  `author_id` BIGINT NOT NULL COMMENT '作者的id',
  `deleted` TINYINT(1) NOT NULL COMMENT '是否被删除',
  `active` TINYINT(1) NOT NULL COMMENT '是否处于激活状态',
  `title` VARCHAR(500) NOT NULL COMMENT '内容标题',
  `slug` VARCHAR(200) NULL COMMENT '内容缩略名',
  `type` VARCHAR(45) NULL COMMENT '内容类别',
  `status` VARCHAR(45) NULL COMMENT '内容状态',
  `tags` VARCHAR(200) NULL COMMENT '标签列表',
  `categories` VARCHAR(200) NULL COMMENT '分类列表',
  `hits` BIGINT NULL COMMENT '点击次数',
  `allow_comment` TINYINT(1) NOT NULL COMMENT '是否允许评论',
  `comments_num` BIGINT NULL COMMENT '内容所属评论数目',
  `allow_ping` TINYINT(1) NOT NULL COMMENT '是否允许ping',
  `allow_feed` TINYINT(1) NOT NULL COMMENT '是否允许出现在聚合中',
  `content` TEXT NULL COMMENT '内容文字',
  `thumb_img` VARCHAR(300) NULL COMMENT '缩略图的地址',
  `fmt_type` VARCHAR(45) NULL COMMENT '是那种格式的，Markdown或者html',
  `created` INT NULL COMMENT '显示的创建时间戳',
  `modified` INT NULL COMMENT '展示的修改时间戳',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `create_by` BIGINT NOT NULL COMMENT '被谁创建',
  `update_by` BIGINT NOT NULL COMMENT '被谁修改',
  PRIMARY KEY (`id`),
  INDEX `fk_contents_users1_idx` (`author_id` ASC),
  FULLTEXT INDEX `fulltext_title` (`title` ASC),
  FULLTEXT INDEX `fulltext_categories` (`categories` ASC),
  FULLTEXT INDEX `fulltext_tags` (`tags` ASC),
  FULLTEXT INDEX `fulltext_content` (`content` ASC),
  FULLTEXT INDEX `fulltext_article` (`title` ASC, `categories` ASC, `tags` ASC, `content` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comments` ;

CREATE TABLE IF NOT EXISTS `comments` (
  `id` BIGINT NOT NULL COMMENT '评论的id',
  `deleted` TINYINT(1) NOT NULL COMMENT '是否被删除',
  `active` TINYINT(1) NOT NULL COMMENT '是否处于激活状态',
  `content_id` BIGINT NOT NULL COMMENT '品论所属内容',
  `author_id` BIGINT NOT NULL COMMENT '评论的作者id\n',
  `parent_id` BIGINT NOT NULL COMMENT '父级评论id',
  `content` TEXT NULL COMMENT '评论内容',
  `type` VARCHAR(45) NULL COMMENT '评论类型',
  `status` VARCHAR(45) NULL COMMENT '评论状态',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `create_by` BIGINT NOT NULL COMMENT '被谁创建',
  `update_by` BIGINT NOT NULL COMMENT '被谁修改',
  PRIMARY KEY (`id`),
  INDEX `fk_comments_contents1_idx` (`content_id` ASC),
  INDEX `fk_comments_users1_idx` (`author_id` ASC),
  INDEX `fk_comments_comments1_idx` (`parent_id` ASC))
ENGINE = InnoDB
COMMENT = '评论表';


-- -----------------------------------------------------
-- Table `links`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `links` ;

CREATE TABLE IF NOT EXISTS `links` (
  `id` BIGINT NOT NULL COMMENT '连接的id',
  `deleted` TINYINT(1) NOT NULL COMMENT '是否被删除',
  `active` TINYINT(1) NOT NULL COMMENT '是否处于激活状态',
  `author_id` BIGINT NOT NULL COMMENT '文件上传者的id',
  `file_name` VARCHAR(200) NULL COMMENT '文件的原名',
  `file_type` VARCHAR(45) NULL COMMENT '文件的种类',
  `file_key` VARCHAR(100) NULL COMMENT '文件在文件服务器上的名称',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `create_by` BIGINT NOT NULL COMMENT '创建者id',
  `update_by` BIGINT NOT NULL COMMENT '修改者id',
  PRIMARY KEY (`id`),
  INDEX `fk_attachs_users1_idx` (`author_id` ASC))
ENGINE = InnoDB
COMMENT = '文件连接表';


-- -----------------------------------------------------
-- Table `metas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metas` ;

CREATE TABLE IF NOT EXISTS `metas` (
  `id` BIGINT NOT NULL COMMENT '主键',
  `deleted` TINYINT(1) NOT NULL COMMENT '是否被删除',
  `active` TINYINT(1) NOT NULL COMMENT '是否处于激活状态',
  `parent_id` BIGINT NOT NULL COMMENT '父级项目',
  `name` VARCHAR(200) NULL COMMENT '项目名称',
  `slug` VARCHAR(100) NULL COMMENT '项目缩略名',
  `type` VARCHAR(45) NULL COMMENT '项目类型',
  `detail` TEXT NULL COMMENT '项目详情',
  `sort` INT NULL COMMENT '排序',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `create_by` BIGINT NOT NULL COMMENT '创建者',
  `update_by` BIGINT NOT NULL COMMENT '修改者',
  PRIMARY KEY (`id`),
  INDEX `fk_metas_metas1_idx` (`parent_id` ASC))
ENGINE = InnoDB
COMMENT = '项目meta数据';


-- -----------------------------------------------------
-- Table `logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `logs` ;

CREATE TABLE IF NOT EXISTS `logs` (
  `id` BIGINT NOT NULL COMMENT '日志的id',
  `deleted` TINYINT(1) NOT NULL COMMENT '是否被删除',
  `active` TINYINT(1) NOT NULL COMMENT '是否处于激活状态',
  `user_id` BIGINT NOT NULL COMMENT '发起人id',
  `ip` VARCHAR(200) NULL COMMENT '访问者id',
  `agent` VARCHAR(500) NULL COMMENT '访问者代理',
  `data` TEXT NULL COMMENT '操作的数据',
  `action` VARCHAR(500) NULL COMMENT '执行的操作',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `create_by` BIGINT NOT NULL COMMENT '被谁创建',
  `update_by` BIGINT NOT NULL COMMENT '被谁修改',
  PRIMARY KEY (`id`),
  INDEX `fk_logs_users1_idx` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `options`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `options` ;

CREATE TABLE IF NOT EXISTS `options` (
  `id` BIGINT NOT NULL,
  `deleted` TINYINT(1) NOT NULL COMMENT '是否被删除',
  `active` TINYINT(1) NOT NULL COMMENT '是否处于激活状态',
  `name` VARCHAR(200) NULL COMMENT '配置名称',
  `value` VARCHAR(2000) NULL COMMENT '配置值',
  `detail` TEXT NULL COMMENT '配置详情',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `create_by` BIGINT NOT NULL COMMENT '被谁创建',
  `update_by` BIGINT NOT NULL COMMENT '被谁修改',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '配置的数据';


-- -----------------------------------------------------
-- Table `content_metas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `content_metas` ;

CREATE TABLE IF NOT EXISTS `content_metas` (
  `id` BIGINT NOT NULL COMMENT '主键',
  `deleted` TINYINT(1) NOT NULL COMMENT '是否被删除',
  `active` TINYINT(1) NOT NULL COMMENT '是否处于激活状态',
  `content_id` BIGINT NOT NULL COMMENT '内容主键',
  `meta_id` BIGINT NOT NULL COMMENT '项目主键',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `create_by` BIGINT NOT NULL COMMENT '被谁创建',
  `update_by` BIGINT NOT NULL COMMENT '被谁修改',
  PRIMARY KEY (`id`),
  INDEX `fk_contents_has_metas_metas1_idx` (`meta_id` ASC),
  INDEX `fk_contents_has_metas_contents1_idx` (`content_id` ASC))
ENGINE = InnoDB
COMMENT = '内容和项目关系';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
